### ISSUE TITLE
ReSharper 2016.2 Support

### ISSUE THREAD

**Issue by ghost** [matkoch/resharper-testlinker#1]
Recompile for ReSharper **2016.2**?

Thx

**Comment by smad2005** [comment]
Thank you very much, Working!!!

**Comment by matkoch** [comment]
@smad2005 Eh :D I'm in the middle of testing it. It's actually not working for me, since the shortcuts are not exposed... Do you have them?

**Comment by smad2005** [comment]
`ctrl+alt+F7` - working well

> Tests can be executed from their linked production code. This feature automatically integrates with the shortcuts for executing unit tests in run, debug, profile, and cover mode.

working too

**Comment by matkoch** [comment]
Okay, I was talking about the two custom ones.

**Comment by smad2005** [comment]
`ReSharper_GotoAllLinkedTypes` and `ReSharper_GotoLinkedTypesWithDerivedName` 
Checked (added to keyboard setting), working too

**Comment by matkoch** [comment]
@SyntonyAustria, @smad2005 I had to change the package id due to some inconveniences in ReSharper... It's now `ReSharper.TestLinker` instead of `TestLinker.ReSharper`... That means that you won't be notified of new versions, as long as you don't reinstall. I unpublished the old id's versions.
