### ISSUE TITLE
2018.1 Installation Error

### ISSUE THREAD

**Issue by Mike-E-angelo** [matkoch/resharper-testlinker#12]
Bummer... looks like I get an error installing this extension. :(

--- EXCEPTION #1/5 [BadImageFormatException]
  Message = “Could not load file or assembly 'file:///C:\Users\..\AppData\Local\JetBrains\~\AppDomainBase\Cexowig\TestLinker.1337.0.0.0.E7BF1C7E\TestLinker.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.”
  
Reported here as well:
https://youtrack.jetbrains.com/issue/RSRP-468428

**Comment by matkoch** [comment]
Just to confirm, this is really an error, and not just a warning? I tried installing just now, and it produces some warnings, but still works after restart. :/

**Comment by Mike-E-angelo** [comment]
Yes it is an error on my machine, unfortunately.  TestLinker does not install and the coveted `ReSharper_GotoAllLinkedTypes` is not available. ☹️

**Comment by Mike-E-angelo** [comment]
Bummer... FWIW I got the idea to install preview Visual Studio and try installing 2018.1 along with TestLinker there.  Unfortunately same error, different path, though:

```
  Message = “Could not load file or assembly 'file:///C:\Users\..\AppData\Local\JetBrains\~\AppDomainBase\Bucybob\TestLinker.1337.0.0.0.E7BF1C7E\TestLinker.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.”
```

**Comment by matkoch** [comment]
Could you check 2018.1.1 of the plugin?

**Comment by Mike-E-angelo** [comment]
OK great... thank you for the push!  Good news is that there were no errors this time, bad news: still no `ReSharper_GotoAllLinkedTypes` keyboard shortcut listed in keyboard options.  Any suggestions on why this might be?

**Comment by Mike-E-angelo** [comment]
UNINSTALL AND REINSTALL FTW!!! Thank you so much @matkoch !!  It's such a warm n' fuzzy keycombo I felt more than naked without it.  Almost to the point of reverting to 2017.3.5. 😆

**Comment by matkoch** [comment]
Great, thanks for the feedback! :)
