### ISSUE TITLE
ReSharper 2018.3 Support?

### ISSUE THREAD

**Issue by Mike-E-angelo** [matkoch/resharper-testlinker#13]
Is this 2018.3, by chance?  I do not see it at present.

**Comment by matkoch** [comment]
Working on it. Is anyone using Rider now and then?

**Comment by matkoch** [comment]
Currently waiting for approval: https://plugins.jetbrains.com/plugin/11717-testlinker

There is now also a Rider version: https://plugins.jetbrains.com/plugin/12022-testlinker

**Comment by Mike-E-angelo** [comment]
Great, thank you!  I didn't see the previous question until now unfortunately.  I did try Rider but had problems with its multimon setup.  I should try it again to see if I can get better luck. :)

**Comment by Mike-E-angelo** [comment]
Quick confirmation here that it works and have it installed.  All is right in the world again. 😁

Thank you for taking the time to make this project and also to jump through the hoops to ensure that it is continuously updated and registered with the latest ReSharper repositories. 👍

**Comment by matkoch** [comment]
@Mike-EEE part of my work basically, but glad you like it :)
