### ISSUE TITLE
ReSharper 2016.3 Support

### ISSUE THREAD

**Issue by smad2005** [matkoch/resharper-testlinker#2]

**Comment by matkoch** [comment]
@smad2005 new version has been uploaded. Could you please tell me if everything works as expected? The API didn't change that much.

**Comment by smad2005** [comment]
Thx for updating, but your package is absent for wave 7
![default](https://cloud.githubusercontent.com/assets/1619549/21289150/5e0bdab6-c49e-11e6-8fc2-fc29de8a91fd.png)

![default](https://cloud.githubusercontent.com/assets/1619549/21289157/7186f418-c49e-11e6-9c6e-986249df2cdf.png)

I love your plugin very much, i think it's one of the best thing for tests (super time saver)

**Comment by smad2005** [comment]
~~I tried to build from github and found issue~~ Fixed setting, built and installed from local folder

![default](https://cloud.githubusercontent.com/assets/1619549/21289261/09f5540e-c4a1-11e6-8e26-de8b97bb5c73.png)

>Could you please tell me if everything works as expected? The API didn't change that much.

Work fine!!!!!!!

**Comment by matkoch** [comment]
Now the package should be there. Forgot to update the nuspec file :)

If you have any idea on how to improve the plugin, let me know.
