### ISSUE TITLE
ReSharper 2017.1 Support

### ISSUE THREAD

**Issue by ulrichb** [matkoch/resharper-testlinker#4]
... we're already ~at EAP~ ~5~ ~6~ after the release date ... 😉

**Comment by smad2005** [comment]
If just update wave version, it will partially works (but no for all classes it could found tests).
Also i see that suffix was changed from `Tests` to `Test`

**Comment by matkoch** [comment]
In gallery now.

**Comment by matkoch** [comment]
@smad2005 I added both suffixes now... `Test` and `Tests` as well as `Spec` and `Specs`... In case of, but probably unlikely, memory issues, it's advisable to change that to the actually used suffixes.
