### ISSUE TITLE
Partial namespace support

### ISSUE THREAD

**Issue by Sam13** [matkoch/resharper-testlinker#5]
If I have the following project structure:

ProjectA
+ Namespace1.Sub1
  + ClassA
  + ClassB
+ Namespace2.Sub2
  + ClassA
  + ClassB

ProjectAUnitTest

+ Namespace1UnitTest.Sub1
  + ClassATest
  + ClassBTest
+ Namespace2UnitTest.Sub2
  + ClassATest
  + ClassBTest

Currently test linker reports all test classes with the same name and it's impossible to recognize the correct one.
![image](https://cloud.githubusercontent.com/assets/2196081/25947331/51f84070-364f-11e7-8fac-0dee3c64ad17.png)

My proposal is to take parts of namespaces in lookup sequence if multiple occurrences are found.
E.g. for `Namespace1.Sub1.ClassA` lookup for tests with `Sub1.ClassA` which will find `Namespace1UnitTest.Sub1.ClassATest` instead of all `ClassATest` classes

**Comment by matkoch** [comment]
Hi @Sam13,

sorry for the late response. As far as I remember, this can't be changed from the plugin side. Can't you just use the `GoToLinkedTypes` action?

**Comment by Sam13** [comment]
You mean _ReSharper->Navigate->Go to all linked types_?
Yes that should work as well.
So I'll have to update my keyboard shortcut ;-)

**Comment by matkoch** [comment]
Just for the record, [this](https://github.com/matkoch/TestLinker/blob/master/src/TestLinker/Navigation/LinkedTypesRelatedFilesProvider.cs#L30) is the code I'm talking about. I'm just passing the `IProjectFile` instance there. Formatting happens inside ReSharper :)
