### ISSUE TITLE
ReSharper 2017.2 Support 

### ISSUE THREAD

**Issue by smad2005** [matkoch/resharper-testlinker#8]

**Comment by smad2005** [comment]
Or Rider support)

**Comment by glconti** [comment]
For the ones having this issue, the code is already updated, it's just the build failing and the binaries not uploaded to the R# gallery.  I just cloned the repo and run the build script to generate the .nupkg package, then follow the steps at https://www.jetbrains.com/help/resharper/sdk/Extensions/Deployment/LocalInstallation/InstallCustomSource.html to install a package from a custom source.

**Comment by matkoch** [comment]
Sorry folks that it took so long. It went forgotten multiple times and I actually thought I didn't even update to the latest SDK yet. I just pushed the package to the gallery. I'm closing this, if anything doesn't feel right, please comment/re-open here.

@smad2005 about Rider support: I can't promise anything as of now. If you need it urgent, you could send a PR. As a reference, I would use the Unity plugin or HeapAllocationViewer.
